[package]
name = "ordermap"
version = "0.2.7"
authors = ["bluss"]
documentation = "https://docs.rs/ordermap/"
repository = "https://github.com/bluss/ordermap"
license = "Apache-2.0/MIT"
description = "A hash table with consistent order and fast iteration."

[lib]
bench = false

[dependencies]
efficient_enum = { version = "^0.3.1", optional = true }

[dev-dependencies]
itertools = "0.5.1"
rand = "0.3"
quickcheck = { version = "0.4", default-features = false }
fnv = "1.0"
lazy_static = "0.2"

[features]
# for testing only, of course
test_low_transition_point = []
test_debug = []
test_efficient_enum = ["efficient_enum", "unsafe"]
test_unsafe_efficient_enum = ["test_efficient_enum"]
test_unsafe_index = ["unsafe"]
unsafe = []

[profile.bench]
debug = true
